spring:
  application:
    name: reactive

  # Enable H2 Console
  h2:
    console:
      enabled: true

  # Database Configuration for H2
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: gex
    password:

  # Schema Generation
  sql:
    init:
      mode: always
      platform: h2
