spring:
  application:
    name: reactive

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/testdb
    username: gex
    password: gex
    pool:
      initial-size: 5
      max-size: 20

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: jdbc:postgresql://localhost:5432/testdb
    user: gex
    password: gex
    enabled: true

logging:
  level:
    root: INFO

server:
  port: 8090